# DO NOT EDIT generated by terraflake

{ ... }:
let
  attrsToList = attrs: builtins.map
    (name: { inherit name; value = attrs.${name}; })
    (builtins.attrNames attrs);
  filterAttrs = fn: attrs:
    let
      list = attrsToList attrs;
      list' = builtins.filter ({ name, value }: fn name value) list;
    in
    builtins.listToAttrs list';

  tfstate = (builtins.fromJSON (builtins.readFile ../terraform.tfstate)).outputs;
  outputs = builtins.mapAttrs (_: value: value.value) tfstate;
  isNodeOutput = name: name == "terraflake" || name == "nixiform";
  meta = filterAttrs (name: _: !(isNodeOutput name)) outputs;
  nodes' = filterAttrs (name: _: isNodeOutput name) outputs;
  nodes = builtins.listToAttrs
    (builtins.map
      (node: { name = node.name; value = node; })
      (nodes'.terraflake or nodes'.nixiform));
in
{
  terraflake.input = {
    inherit meta nodes;
  };
}
