# DO NOT EDIT generated by terraflake
{ terraform, jq, runCommand, terraflake-terraform-state ? ../terraform.tfstate }:

runCommand "terraflake-terraform-local-output"
{
  buildInputs = [ terraform jq ];
}
  ''
    terraform output -json -state="${terraflake-terraform-state}" \
    | jq > $out -rM '
    {
      meta: (to_entries
        | map(select(.key | test("^terraflake$") | not))
        | map({ (.key): .value.value })
        | add // {}),
      nodes: ([.terraflake.value]
        | flatten
        | map(select(.name!=null and .ip!=null and .ssh_key!=null))
        | map({ (.name): . })
        | add // {})
    }
    '
  ''
