# DO NOT EDIT generated by terraflake

{ pkgs, ... }:
let
  inherit (pkgs) terraform jq runCommand;
  drv = runCommand "terraflake-terraform-local-output"
    {
      buildInputs = [ terraform jq ];
    }
    ''
      terraform output -json -state="${../terraform.tfstate}" \
      | jq > $out -rM '
      {
        meta: (to_entries
          | map(select(.key | test("^terraflake$") | not))
          | map({ (.key): .value.value })
          | add // {}),
        nodes: ([.terraflake.value]
          | flatten
          | map(select(.name!=null and .ip!=null and .ssh_key!=null))
          | map({ (.name): . })
          | add // {})
      }
      '
    '';
  input = pkgs.lib.importJSON drv;
in
{
  nixiform.input = input;
  terraflake.input = input;
  tonix.input = input;
}
