#!/usr/bin/env bash
set -eo pipefail

# Taken from nixos-infect
# More info at: https://github.com/elitak/nixos-infect

infect() {
  # Remove nix installed with curl | bash
  rm -fv /nix/var/nix/profiles/default*
  /nix/var/nix/profiles/system/sw/bin/nix-collect-garbage

  # Reify resolv.conf
  [[ -L /etc/resolv.conf ]] \
    && mv -v /etc/resolv.conf /etc/resolv.conf.lnk \
    && cat /etc/resolv.conf.lnk > /etc/resolv.conf

  # Stage the Nix coup d'état
  touch /etc/NIXOS
  echo etc/nixos                   > /etc/NIXOS_LUSTRATE
  echo etc/resolv.conf            >> /etc/NIXOS_LUSTRATE
  echo root/.nix-defexpr/channels >> /etc/NIXOS_LUSTRATE

  rm -rf /boot.bak
  mv -v /boot /boot.bak

  /nix/var/nix/profiles/system/bin/switch-to-configuration boot
}

hasNix() {
  [ -f /etc/NIXOS ] \
    || [ -n "$NIX_PATH" ] \
    || [ -f "$HOME"/.nix-profile/etc/profile.d/nix.sh ]
}

switch() {
  local configPath; configPath="$1"

  # shellcheck disable=SC1090
  [ -n "$NIX_PATH" ] || source "$HOME"/.nix-profile/etc/profile.d/nix.sh

  nix-env --set "$configPath" -p /nix/var/nix/profiles/system

  [ -f /etc/NIXOS ] || infect

  /nix/var/nix/profiles/system/bin/switch-to-configuration switch
}

[ -z "$*" ] || "${1#_}" "${@:2}"
