#!/usr/bin/env bash
set -eo pipefail

# Taken from nixos-infect
# More info at: https://github.com/elitak/nixos-infect

infect() {
  # Remove nix installed with curl | bash
  rm -fv /nix/var/nix/profiles/default*
  /nix/var/nix/profiles/system/sw/bin/nix-collect-garbage

  # Reify resolv.conf
  [[ -L /etc/resolv.conf ]] \
    && mv -v /etc/resolv.conf /etc/resolv.conf.lnk \
    && cat /etc/resolv.conf.lnk > /etc/resolv.conf

  # Stage the Nix coup d'état
  touch /etc/NIXOS
  echo etc/nixos                   > /etc/NIXOS_LUSTRATE
  echo etc/resolv.conf            >> /etc/NIXOS_LUSTRATE
  echo root/.nix-defexpr/channels >> /etc/NIXOS_LUSTRATE

  efivar=$(ls /sys/firmware/efi/efivars/LoaderDevicePartUUID* 2>/dev/null)
  efipart=""
  if [ -n "$efivar" ]; then
    # read efi var using only "standard" utilities. first four bytes are attributes,
    # followed by a utf-16 null-terminated string
    efipart=$(dd if="$efivar" bs=1 skip=4 2>/dev/null | iconv -f utf16 | xargs -l -0)
  fi
  echo "efivar = $efivar" >&2
  echo "efipart = $efipart" >&2
  if findmnt /boot >/dev/null; then
    cp -vr /boot /boot.bak
    if findmnt /boot/efi >/dev/null; then
      [ -z "$efipart" ] && efipart=$(findmnt -n /boot/efi -o partuuid)
      echo "efipart = $efipart" >&2
      umount /boot/efi
    fi
    umount /boot
  else
    mv -v /boot /boot.bak
  fi

  if [ -n "$efipart" ]; then
    mkdir -p /boot
    mount "/dev/disk/by-partuuid/$efipart" /boot
  fi

  ln -s "$(readlink -f /nix/var/nix/profiles/system)" /run/current-system

  /nix/var/nix/profiles/system/bin/switch-to-configuration boot
}

hasNix() {
  [ -f /etc/NIXOS ] \
    || [ -n "$NIX_PATH" ] \
    || [ -f "$HOME"/.nix-profile/etc/profile.d/nix.sh ]
}

switch() {
  local op; op="$1"
  local configPath; configPath="$2"

  # shellcheck disable=SC1090 disable=SC1091
  [ -n "$NIX_PATH" ] || source "$HOME"/.nix-profile/etc/profile.d/nix.sh

  nix-env --set "$configPath" -p /nix/var/nix/profiles/system

  [ -f /etc/NIXOS ] || {
    [ "$op" = "switch" ] || exit 200
    infect
  }

  /nix/var/nix/profiles/system/bin/switch-to-configuration "$op"
}

[ -z "$*" ] || "${1#_}" "${@:2}"
