#!/usr/bin/env bash
set -eo pipefail

hasNix() {
  [ -f /etc/NIXOS ] \
    || [ -n "$NIX_PATH" ] \
    || [ -f "$HOME"/.nix-profile/etc/profile.d/nix.sh ]
}

switch() {
  local op; op="$1"
  local configPath; configPath="$2"

  hasNix || exit 200

  # shellcheck disable=SC1090 disable=SC1091
  [ -n "$NIX_PATH" ] || source "$HOME"/.nix-profile/etc/profile.d/nix.sh

  nix-env --set "$configPath" -p /nix/var/nix/profiles/system

  /nix/var/nix/profiles/system/bin/switch-to-configuration "$op"
}

[ -z "$*" ] || "${1#_}" "${@:2}"
