#!/usr/bin/env bash
set -eo pipefail

makeConfiguration() {
  cat << EOF
{ ... }: {
  imports = [
    "\${nodeConf'.modulesPath}/virtualisation/amazon-image.nix"
  ];
  ec2.hvm = true;
}
EOF
}

makeConfiguration
