#!/usr/bin/env bash
set -eo pipefail

# Taken from nixos-infect
# More info at: https://github.com/elitak/nixos-infect

makeConfiguration() {
  local grubdev
  for grubdev in /dev/vda /dev/sda; do [[ -e $grubdev ]] && break; done

  rootfsdev=$(mount | grep "on / type" | awk '{print $1;}')

  cat << EOF
{ ... }: {
  require = [
    "\${nixpkgsPath}/nixos/modules/profiles/qemu-guest.nix"
  ];
  boot.loader.grub.device = "$grubdev";
  fileSystems."/" = { device = "$rootfsdev"; fsType = "ext4"; };
}
EOF
}

makeConfiguration
